// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO chirps (id, created_at, updated_at, body, user_id)
VALUES (
    gen_random_uuid(), NOW(), NOW(), $1, $2
)
RETURNING id, created_at, updated_at, body, user_id
`

type CreateChirpParams struct {
	Body   string
	UserID uuid.UUID
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp, arg.Body, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const deleteChirpByIDAndUser = `-- name: DeleteChirpByIDAndUser :exec
delete from chirps where id = $1
`

func (q *Queries) DeleteChirpByIDAndUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirpByIDAndUser, id)
	return err
}

const getAllChirps = `-- name: GetAllChirps :many
select id, created_at, updated_at, body, user_id from chirps
order by 
case when $1 = 'asc' then created_at end asc,
case when $1 = 'desc' then created_at end desc
`

func (q *Queries) GetAllChirps(ctx context.Context, dollar_1 interface{}) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getAllChirps, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChirpbyID = `-- name: GetChirpbyID :one
select id, created_at, updated_at, body, user_id from chirps
where id = $1
order by created_at asc
`

func (q *Queries) GetChirpbyID(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirpbyID, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getChirpbyIDCorrectUser = `-- name: GetChirpbyIDCorrectUser :one
select id, created_at, updated_at, body, user_id from chirps
where id = $1 and user_id = $2
order by created_at asc
`

type GetChirpbyIDCorrectUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetChirpbyIDCorrectUser(ctx context.Context, arg GetChirpbyIDCorrectUserParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirpbyIDCorrectUser, arg.ID, arg.UserID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}

const getChirpsbyUserID = `-- name: GetChirpsbyUserID :many
select id, created_at, updated_at, body, user_id from chirps
where user_id = $1
order by 
case when $2 = 'asc' then created_at end asc,
case when $2 = 'desc' then created_at end desc
`

type GetChirpsbyUserIDParams struct {
	UserID  uuid.UUID
	Column2 interface{}
}

func (q *Queries) GetChirpsbyUserID(ctx context.Context, arg GetChirpsbyUserIDParams) ([]Chirp, error) {
	rows, err := q.db.QueryContext(ctx, getChirpsbyUserID, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirp
	for rows.Next() {
		var i Chirp
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Body,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
