// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addRefreshToken = `-- name: AddRefreshToken :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at, revoked_at)
VALUES (
    $1, NOW(), NOW(), $2, $3, null
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type AddRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, addRefreshToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const checkTokenAndGetUser = `-- name: CheckTokenAndGetUser :one
select user_id, refresh_tokens.expires_at as tokenExpiresAt, refresh_tokens.revoked_at as tokenRevokedAt from users 
full join refresh_tokens on users.user_id = refresh_tokens.user_id
where refresh_tokens.token = $1
`

type CheckTokenAndGetUserRow struct {
	UserID         uuid.NullUUID
	Tokenexpiresat sql.NullTime
	Tokenrevokedat sql.NullTime
}

func (q *Queries) CheckTokenAndGetUser(ctx context.Context, token string) (CheckTokenAndGetUserRow, error) {
	row := q.db.QueryRowContext(ctx, checkTokenAndGetUser, token)
	var i CheckTokenAndGetUserRow
	err := row.Scan(&i.UserID, &i.Tokenexpiresat, &i.Tokenrevokedat)
	return i, err
}
